<?php

namespace App\Support;

use Illuminate\Support\Facades\Cache;

/**
 * Helpers for responsive images without a build step: WebP siblings
 * (photo.jpg -> photo.webp, generated by ImageOptimizer / images:webp) and
 * cached intrinsic dimensions for width/height attributes (no CLS).
 */
final class Images
{
    /** Absolute filesystem path for a same-origin asset URL or a relative public path; null for foreign URLs. */
    public static function localPath(?string $url): ?string
    {
        if (! $url) {
            return null;
        }

        $path = $url;

        if (preg_match('#^https?://#i', $url)) {
            $host = parse_url($url, PHP_URL_HOST);
            $ownHosts = array_filter([parse_url((string) config('app.url'), PHP_URL_HOST), request()?->getHost()]);

            if (! in_array($host, $ownHosts, true)) {
                return null;
            }

            $path = (string) parse_url($url, PHP_URL_PATH);
        }

        $path = urldecode(ltrim(strtok($path, '?') ?: '', '/'));

        if ($path === '' || str_contains($path, '..')) {
            return null;
        }

        $full = public_path($path);

        return is_file($full) ? $full : null;
    }

    /** URL of the WebP sibling when it exists, otherwise null. */
    public static function webpUrl(?string $url): ?string
    {
        $local = self::localPath($url);

        if (! $local || ! preg_match('/\.(jpe?g|png)$/i', $local)) {
            return null;
        }

        $webp = preg_replace('/\.(jpe?g|png)$/i', '.webp', $local);

        if (! is_file($webp)) {
            return null;
        }

        return preg_replace('/\.(jpe?g|png)(\?.*)?$/i', '.webp$2', $url);
    }

    /** @return array{0:int,1:int}|null intrinsic [width, height], cached by path + mtime */
    public static function dimensions(?string $url): ?array
    {
        $local = self::localPath($url);

        if (! $local) {
            return null;
        }

        $key = 'imgdim:'.md5($local.'|'.@filemtime($local));

        return Cache::rememberForever($key, function () use ($local) {
            $info = @getimagesize($local);

            return $info ? [(int) $info[0], (int) $info[1]] : null;
        });
    }

    /**
     * Write photo.webp next to photo.jpg/png (skipped when up to date).
     * Returns the webp path or null when the source cannot be converted.
     */
    public static function makeWebp(string $fullPath, int $quality = 80): ?string
    {
        if (! is_file($fullPath) || ! preg_match('/\.(jpe?g|png)$/i', $fullPath) || ! function_exists('imagewebp')) {
            return null;
        }

        $webp = preg_replace('/\.(jpe?g|png)$/i', '.webp', $fullPath);

        if (is_file($webp) && filemtime($webp) >= filemtime($fullPath)) {
            return $webp;
        }

        $info = @getimagesize($fullPath);
        if (! $info) {
            return null;
        }

        $image = match ($info[2]) {
            IMAGETYPE_JPEG => @imagecreatefromjpeg($fullPath),
            IMAGETYPE_PNG => @imagecreatefrompng($fullPath),
            default => null,
        };

        if (! $image) {
            return null;
        }

        if ($info[2] === IMAGETYPE_PNG) {
            imagepalettetotruecolor($image);
            imagealphablending($image, true);
            imagesavealpha($image, true);
        }

        $ok = imagewebp($image, $webp, $quality);
        imagedestroy($image);

        return $ok ? $webp : null;
    }
}
